#!/usr/bin/env python

"""
Input : Fastq file 
        Length of the kmers
Output: A frequency distribution of the kmers
"""

from sys import argv, stderr, stdin, exit, stdout
from getopt import getopt, GetoptError

import string

__author__ = "Aakrosh Ratan"
__email__  = "ratan@bx.psu.edu"

# do we want the debug information to be printed?
debug_flag = False

class fsequence:
    def __init__(self, name, seq):
        self.name = name
        self.seq  = seq

    def __str__(self):
        string  = ">%s\n" % self.name
        string += "%s" % self.seq
        return string

    def __len__(self):
        assert len(self.seq) == len(self.qual)
        return len(self.seq)

class fseq:
    def __init__(self, filename):
        file = open(filename, "r")
        line = file.readline()
        if line[0] == "@":
            self.format = "fastq"
        elif line[0] == ">":
            self.format = "fasta"
        else:
            print >> stderr, "Unhandled format"
        file.close()

        self.file = open(filename, "r")
        self.fqsequence = None
        self.cache = None

    def __del__(self):
        self.file.close()

    def __iter__(self):
        return self

    def close(self):
        self.file.close()

    def next(self):
        if self.format == "fastq":
            line = self.file.readline()
            if not line:
                self.file.close()
                raise StopIteration
            assert line[0] == "@", "header should begin with a @ in a fastq file"
            name = line[1:-1]
            
            line = self.file.readline()
            seq = line[:-1].upper()
            
            line = self.file.readline()
            assert line[0] == "+", \
            "separator line in fastq file should begin with a +"

            line = self.file.readline()
            qual = line[:-1]

            self.sequence = fsequence(name, seq)
        elif self.format == "fasta":
            if self.cache != None:
                line = self.cache
            else:
                line = self.file.readline()
                
            if len(line) == 0:
                self.file.close()
                raise StopIteration
            assert line[0] == ">", "header should start with a > in a fasta file"
            assert line[-1] == "\n"
            name = line[1:-1]
            
            sequence = ""
            line = self.file.readline()

            while line[0] !=  ">" :
                sequence += line.strip()
                # if there is a gap in the sequence (which would be the case 
                # if the fasta sequence was of quality values)
                if(line.find(" ")) != -1:
                    sequence += " "

                line = self.file.readline()
                if len(line) == 0:
                    break

            self.cache = line
            self.sequence = fsequence(name, sequence)
        else:
            print >> stderr, "Should not happen"    

        return self

def reverse_complement(seq):
    complement = string.maketrans('atcgnATCGN', 'tagcnTAGCN')
    return seq.translate(complement)[::-1]

def ConvertStringToKmer(word):
    kmer = 0
    for i,w in enumerate(word):
        if w == "A":
            kmer += 0
        elif w == "C":
            kmer += 1
        elif w == "G":
            kmer += 2
        elif w == "T":
            kmer += 3
        else:
            print >> stderr, "Unknown base: %s" % w
            exit(5)
        if i != (len(word) - 1):
            kmer = kmer << 2
    return kmer

def ConvertKmerToString(kmer, klength):
    word = ""
    for i in range(0, 2*klength, 2):
        mask = pow(2,i) + pow(2,i+1)
        repr = kmer & mask         
        for j in range(0, i/2):
            repr = repr >> 2
        if repr == 0:
            word += "A"
        elif repr == 1:
            word += "C"
        elif repr == 2:
            word += "G"
        elif repr == 3:
            word += "T"
    return word[::-1]

def main(klength, filename, printFrequencies):
    kmers = {}

    num_sequences_processed = 0
    records = fseq(filename)

    for r in records:
        s = r.sequence
    
        for i in range(0, len(s.seq) - klength + 1):
            kmer = s.seq[i:i+klength]
            
            # replace all N's with A's
            kmer = kmer.replace("N","A")

            reversekmer = reverse_complement(kmer)

            if kmer < reversekmer:
                stored = kmer
            else:
                stored = reversekmer
            
            # convert to a more concise representation
            stored_kmer = ConvertStringToKmer(stored)

            if stored_kmer not in kmers:
                kmers[stored_kmer] = 0
            kmers[stored_kmer] += 1

        num_sequences_processed += 1
        if num_sequences_processed % 1000 == 0:
            print >> stderr, "Processed %d sequences" % num_sequences_processed

    records.close()
    print >> stderr, "Counted %d kmers" % len(kmers)

    if printFrequencies == True:
        frequency = {}

        for kmer,kmerCount in kmers.items():
            if kmerCount not in frequency:
                frequency[kmerCount] = 0
            frequency[kmerCount] += 1
      
        for k,v in frequency.items():
            print ConvertKmerToString(k, klength),v
    else:
        keys = kmers.keys()
        for kmer in keys:
            print ConvertKmerToString(kmer, klength), kmers[kmer]
    
def usage():
    f = stderr
    print >> f, "usage:"
    print >> f, "simple_kmer_counter  [options] klength reads.fq "
    print >> f, "where the options are:"
    print >> f, "-h,--help : print usage and quit"
    print >> f, "-d,--debug: print debug information"
    print >> f, "-f,--freqs: print the kmer frequency distribution"

if __name__ == "__main__":
    try:
        opts, args = getopt(argv[1:], "hdf",["help", "debug", "freqs"])
    except GetoptError, err:
        print str(err)
        usage()
        exit(2) 

    printFrequencies = False
    
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            exit()
        elif o in ("-d", "--debug"):
            debug_flag = True
        elif o in ("-f", "--freqs"):
            printFrequencies = True     
        else:
            assert False, "unhandled option"

    if len(args) != 2:
        usage()
        exit(3)

    main(int(args[0]), args[1], printFrequencies)
